### ISSUE TITLE
[GLITCH]- Soro's V3 - Walking up the stairs with Plates/Bowls. 

### ISSUE THREAD

**Issue by JustThomasMD** [Spearritt/Soros-Bug-Log#18]
Hi! I'd like to make you aware that sometimes, when walking up the stairs/steps with a Plate/Bowl equipped in your Robloxians hands you can sometimes glitch and get stuck in the barriers on the steps. A photo of the glitch can be found here: 
![img_0883](https://user-images.githubusercontent.com/31548460/29981671-81051b36-8f46-11e7-98fe-49f02defe9d0.PNG)

**Comment by Pepestan** [comment]
This is because of the already fixed CanCollide, my dude. @Spearritt
