### ISSUE TITLE
OMG FLIPPIN FLYING BOATS OMG

### ISSUE THREAD

**Issue by L11nk** [Spearritt/Soros-Bug-Log#22]
YE I SAW DAT MUTHA FUCKA LINK BYPASSING THE BOAT HE WAS RIGHT IN THE GOD DAMN RESTURANT GOD FLIPIN DAM IT. PATCH IT U FAT PIECE OF MINECRAFT SAM

_**-Link**_
_**that one homeless man succer**_

**Comment by L11nk** [comment]
I FORGET TO ADD SOMETHING

IM GAY FOR HOMELESS MEN.

**Comment by lamayII** [comment]
Fix this now!!1111 or dislike

**Comment by L11nk** [comment]
YE ME222 FLIP UU SAM U FAT PIECE OF MINECRAFT2
