### ISSUE TITLE
Applicants unable to see 'Trainee' rank above their head when refreshed at the IC.

### ISSUE THREAD

**Issue by Felonna** [Spearritt/Soros-Bug-Log#24]
It has happened to me several times already that whenever someone promotes the applicants I interview and I refresh them, for some reason the 'Trainee' rank does not appear above their head. I always have to tell them that it's not visible at the IC but it will be at the restaurant. I wonder if this can be fixed?

**Comment by Felonna** [comment]
Also, with some applicants it's possible to refresh them and with others it isn't. Another HR told me it could be because of the package that they're wearing? I honestly have no clue.

**Comment by lamayII** [comment]
Probably a problem with wait time from ROBLOX itself or you are spelling their name wrong. Interview Servers get flooded easily so it get's slower than other servers

**Comment by Felonna** [comment]
Well it definitely isn't because of spelling their usernames wrong, because when I refresh them, a notification always pops up saying: "Refreshed the following user(s): ..." so I can check if their username is correct, yet still the rank doesn't pop up.
